services:
  - type: web
    name: investsmart-frontend
    env: python
    plan: free
    buildCommand: cd investsmart_web/frontend && pip install -r requirements.txt
    startCommand: cd investsmart_web/frontend && streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    rootDir: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
